FROM ubuntu:18.04
MAINTAINER PNU PNU@PNU.COM

RUN apt-get update
RUN apt-get install -y gcc g++ python python3
RUN apt-get install -y software-properties-common
RUN apt-get install -y locales
RUN locale-gen ko_KR.UTF-8
ENV LC_ALL ko_KR.UTF-8

RUN rm -rf /var/lib/apt/lists/*
